# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "A comprehensive command-line interface for Bitbucket."
  homepage "https://github.com/hugs7/bitbucket-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.1.0/bb_0.1.0_darwin_amd64.tar.gz"
      sha256 "1c03653b4491c2d0b8962b644270802773fc37706530d96e85dae04a32549fc0"

      define_method(:install) do
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.1.0/bb_0.1.0_darwin_arm64.tar.gz"
      sha256 "a27d2ace5cf78f12cdb9722196b9a3aad32f9636b527dd1ca494312661baa583"

      define_method(:install) do
        bin.install "bb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.1.0/bb_0.1.0_linux_amd64.tar.gz"
      sha256 "0ae472c6e7aa37a0cf78666183cc10a43007b8f04d79114c58950f656b808ed3"
      define_method(:install) do
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.1.0/bb_0.1.0_linux_arm64.tar.gz"
      sha256 "f0150b433634c4b90c07c9d7c3d010ea8d1caf1d4140e9137a993fc16e79966d"
      define_method(:install) do
        bin.install "bb"
      end
    end
  end

  test do
    system "#{bin}/bb version"
  end
end
