# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "A comprehensive command-line interface for Bitbucket."
  homepage "https://github.com/hugs7/bitbucket-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.1.0/bb_0.1.0_darwin_amd64.tar.gz"
      sha256 "5bf6996c3aca0ad429fb26d2374ed0851fcdda1f72d605837770bad0992a901d"

      define_method(:install) do
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.1.0/bb_0.1.0_darwin_arm64.tar.gz"
      sha256 "cc14342d437d424bdc8f648e497a4ddc144d0c30d8b70f8d2a93d1a53d1bc440"

      define_method(:install) do
        bin.install "bb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.1.0/bb_0.1.0_linux_amd64.tar.gz"
      sha256 "e157ed1a8dfc5a14a8ec98f2c3a053d1442300ffee36015f76d84d327b2eb222"
      define_method(:install) do
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.1.0/bb_0.1.0_linux_arm64.tar.gz"
      sha256 "b9670f29bf17f2a4aeb5382ca1975c984967738399c0033c165b3c4d6a6384b5"
      define_method(:install) do
        bin.install "bb"
      end
    end
  end

  test do
    system "#{bin}/bb version"
  end
end
