# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "A comprehensive command-line interface for Bitbucket."
  homepage "https://github.com/hugs7/bitbucket-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.2.0/bb_0.2.0_darwin_amd64.tar.gz"
      sha256 "1ce6fde6c47cfd811a30b2bed025efe7e4eec15da9d383cd8899f79af25a27f4"

      define_method(:install) do
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.2.0/bb_0.2.0_darwin_arm64.tar.gz"
      sha256 "cf2ececdbe344f48d70ff93ed0f2c735e4a46334cb36023bcbdae72f69ae29b7"

      define_method(:install) do
        bin.install "bb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.2.0/bb_0.2.0_linux_amd64.tar.gz"
      sha256 "1160b1fc289a7ca72400159b4dde164211c944bea044b3f7ad540d6b41782cdc"
      define_method(:install) do
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.2.0/bb_0.2.0_linux_arm64.tar.gz"
      sha256 "772f150012716543c60968c6263e74c8c3f2e62dd9d18c4e5a80d5c8a805e91a"
      define_method(:install) do
        bin.install "bb"
      end
    end
  end

  test do
    system "#{bin}/bb version"
  end
end
