# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BitbucketCli < Formula
  desc "A comprehensive command-line interface for Bitbucket."
  homepage "https://github.com/hugs7/bitbucket-cli"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.8.0/bb_0.8.0_darwin_amd64.tar.gz"
      sha256 "2a3652581609324f7ebf0ad0e7a972c71471221fff684441b6a608e5e88f70ae"

      define_method(:install) do
        bin.install "bb"
        bash_completion.install "completions/bb.bash" => "bb"
        zsh_completion.install "completions/_bb"
        fish_completion.install "completions/bb.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.8.0/bb_0.8.0_darwin_arm64.tar.gz"
      sha256 "101dc386b73dc0c4eef9ebc778212ccfbc98938da05eb1d9d466e085e194f2ba"

      define_method(:install) do
        bin.install "bb"
        bash_completion.install "completions/bb.bash" => "bb"
        zsh_completion.install "completions/_bb"
        fish_completion.install "completions/bb.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.8.0/bb_0.8.0_linux_amd64.tar.gz"
      sha256 "b323ebc75bd6327534b9acad921f15dd55ef46349f4771dbe1539265e68b85d9"
      define_method(:install) do
        bin.install "bb"
        bash_completion.install "completions/bb.bash" => "bb"
        zsh_completion.install "completions/_bb"
        fish_completion.install "completions/bb.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.8.0/bb_0.8.0_linux_arm64.tar.gz"
      sha256 "638cdd0e134618e036036d1c02d8f6da6815028c9b491dff4e0172eb5275427e"
      define_method(:install) do
        bin.install "bb"
        bash_completion.install "completions/bb.bash" => "bb"
        zsh_completion.install "completions/_bb"
        fish_completion.install "completions/bb.fish"
      end
    end
  end

  test do
    system "#{bin}/bb version"
  end
end
