# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BitbucketCli < Formula
  desc "A comprehensive command-line interface for Bitbucket."
  homepage "https://github.com/hugs7/bitbucket-cli"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.11.0/bb_0.11.0_darwin_amd64.tar.gz"
      sha256 "4fc7aabfa0a12c330a578544f8e5779b5b349fceacf87fbac5e9953b809dc391"

      define_method(:install) do
        bin.install "bb"
        bash_completion.install "completions/bb.bash" => "bb"
        zsh_completion.install "completions/_bb"
        fish_completion.install "completions/bb.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.11.0/bb_0.11.0_darwin_arm64.tar.gz"
      sha256 "d944ca959acd5540914d6f3fc57ae7e7436edfba814ab4d5da7e6e730ca9be14"

      define_method(:install) do
        bin.install "bb"
        bash_completion.install "completions/bb.bash" => "bb"
        zsh_completion.install "completions/_bb"
        fish_completion.install "completions/bb.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.11.0/bb_0.11.0_linux_amd64.tar.gz"
      sha256 "0f0fbc1aeeed6f05245592d990cb3f765930fc492c54dd9d094702b197ca6eb4"
      define_method(:install) do
        bin.install "bb"
        bash_completion.install "completions/bb.bash" => "bb"
        zsh_completion.install "completions/_bb"
        fish_completion.install "completions/bb.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.11.0/bb_0.11.0_linux_arm64.tar.gz"
      sha256 "dc2f301fa74601d5a40960c8c55bab8fe36e2d7743cc6bb77450a3aaeae9051e"
      define_method(:install) do
        bin.install "bb"
        bash_completion.install "completions/bb.bash" => "bb"
        zsh_completion.install "completions/_bb"
        fish_completion.install "completions/bb.fish"
      end
    end
  end

  test do
    system "#{bin}/bb version"
  end
end
