# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BitbucketCli < Formula
  desc "A comprehensive command-line interface for Bitbucket."
  homepage "https://github.com/hugs7/bitbucket-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.4.0/bb_0.4.0_darwin_amd64.tar.gz"
      sha256 "eccc6b9cbabe742b32dd163ef8fc4d8d4fd8ea6ac373f8f0fb06a57c43366822"

      define_method(:install) do
        bin.install "bb"
        bash_completion.install "completions/bb.bash" => "bb"
        zsh_completion.install "completions/_bb"
        fish_completion.install "completions/bb.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.4.0/bb_0.4.0_darwin_arm64.tar.gz"
      sha256 "a8be857cfec37cf92c949cf9dbec337c45865b086f3f2864694bd61d6d421535"

      define_method(:install) do
        bin.install "bb"
        bash_completion.install "completions/bb.bash" => "bb"
        zsh_completion.install "completions/_bb"
        fish_completion.install "completions/bb.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.4.0/bb_0.4.0_linux_amd64.tar.gz"
      sha256 "02c0654307c8254e5fce39e578c14677e322c60eb0661d3e28f8b379c077debe"
      define_method(:install) do
        bin.install "bb"
        bash_completion.install "completions/bb.bash" => "bb"
        zsh_completion.install "completions/_bb"
        fish_completion.install "completions/bb.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugs7/bitbucket-cli/releases/download/v0.4.0/bb_0.4.0_linux_arm64.tar.gz"
      sha256 "cf43407d2949cc0cbf5eedfbe2a03bfcb1243a4c8739f1a9b53f4756cd6028a9"
      define_method(:install) do
        bin.install "bb"
        bash_completion.install "completions/bb.bash" => "bb"
        zsh_completion.install "completions/_bb"
        fish_completion.install "completions/bb.fish"
      end
    end
  end

  test do
    system "#{bin}/bb version"
  end
end
