# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JiraCli < Formula
  desc "A fast, comprehensive command-line interface and TUI for Jira."
  homepage "https://github.com/hugs7/jira-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugs7/jira-cli/releases/download/v0.3.0/jr_0.3.0_darwin_amd64.tar.gz"
      sha256 "977fb84712cb77d20d614e520c986e3379ef6ebb9e66a60f130d407ba4236b6f"

      define_method(:install) do
        bin.install "jr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugs7/jira-cli/releases/download/v0.3.0/jr_0.3.0_darwin_arm64.tar.gz"
      sha256 "c1b552bf44fbf3e603fd03c12f950461a3f33d84e0676a3ac20f99f7225d84da"

      define_method(:install) do
        bin.install "jr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugs7/jira-cli/releases/download/v0.3.0/jr_0.3.0_linux_amd64.tar.gz"
      sha256 "65c8c1e319da9f7550346b2874c3aedc11d1f4714dbd405f5ac7911a5d67b002"
      define_method(:install) do
        bin.install "jr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugs7/jira-cli/releases/download/v0.3.0/jr_0.3.0_linux_arm64.tar.gz"
      sha256 "9b42442a3b57776bcaf9db517e6ddbfab58ff5d0af95432a6a4fc4c5d4b16301"
      define_method(:install) do
        bin.install "jr"
      end
    end
  end

  test do
    system "#{bin}/jr version"
  end
end
