# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JiraCli < Formula
  desc "A fast, comprehensive command-line interface and TUI for Jira."
  homepage "https://github.com/hugs7/jira-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugs7/jira-cli/releases/download/v0.1.0/jr_0.1.0_darwin_amd64.tar.gz"
      sha256 "039aa4d1a10c1850c48deff1ad85f894c1d3c0e79f425e6d9eb920031b7e0dc8"

      define_method(:install) do
        bin.install "jr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugs7/jira-cli/releases/download/v0.1.0/jr_0.1.0_darwin_arm64.tar.gz"
      sha256 "716c6165e9040610fdd600ff1e68de8750d847f8978bd422b6214729dc87513a"

      define_method(:install) do
        bin.install "jr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugs7/jira-cli/releases/download/v0.1.0/jr_0.1.0_linux_amd64.tar.gz"
      sha256 "8bd9acdaaee17cd0d0c75ea3b6b7b0f726db2b1680fd477e83d5a3f8628b759c"
      define_method(:install) do
        bin.install "jr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugs7/jira-cli/releases/download/v0.1.0/jr_0.1.0_linux_arm64.tar.gz"
      sha256 "773633c8108576e29d6b20a83336a8ae015766fd8d2f06b5d4a4ac802cd742cb"
      define_method(:install) do
        bin.install "jr"
      end
    end
  end

  test do
    system "#{bin}/jr version"
  end
end
